# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_cli.ipynb.

from __future__ import annotations

import argparse


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="{{ description }}")
    parser.add_argument("--name", help="Optional name to greet.")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    name = args.name or "World"
    print(f"Hello {name}!")
    return 0


__all__ = ["build_parser", "main"]
